### ISSUE TITLE
Image Fails to Boot

### ISSUE THREAD

**Issue by smp** [wednesdayayay/Scrawl#4]
Really excited to use your tool, but I couldn't get it to boot from a raspi 3b+

1. Downloaded zip from https://drive.google.com/file/d/1ep0ZNawBRCll6pyFvFSpVqMtxO2fa4qM/view
2. Extracted
3. Successfully flashed to SD card with Balena Etcher v1.14.3 (latest)
4. Inserted SD card and booted

Error received is: /etc/init exists, but could not execute it error

**Comment by smp** [comment]
For anyone else who runs into this issue, the uncompressed image worked just fine.


https://drive.google.com/file/d/1vKiNYV4l9_f-cTYtPmeCfq20c2seEjrJ/view?usp=sharing

**Comment by wednesdayayay** [comment]
sorry about that!
yeah I need to dig back into scrawl here pretty soon and make a version that works over HDMI out instead of composite.
At that point I'll consolidate all the links and documentation and do a new overview video with the new streaming setup and hardware system setup.

I've got about a month of integrating software back into the hardware setup to tackle first and then I'm going to get back into some actual software programming. 

Honestly I'll try to start with scrawl because I don't intend on continuing to use open frameworks. I love that this is standalone and on a RPI but I just like working in touchdesigner so much more.

I will be releasing a Scrawl for TD as well.

**Comment by wednesdayayay** [comment]
sorry about that!
yeah I need to dig back into scrawl here pretty soon and make a version that works over HDMI out instead of composite.
At that point I'll consolidate all the links and documentation and do a new overview video with the new streaming setup and hardware system setup.

I've got about a month of integrating software back into the hardware setup to tackle first and then I'm going to get back into some actual software programming.

Honestly I'll try to start with scrawl because I don't intend on continuing to use open frameworks. I love that this is standalone and on a RPI but I just like working in touchdesigner so much more.

I will be releasing a Scrawl for TD as well.
